### ISSUE TITLE
Basic transformation summary and custom fail conditions

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#452]
The goal here is to be enable a user to specify under what conditions a transformation is successful, and allow him to easily evaluate if it was successful under these conditions or not.

The idea is to add support for a transformation summary, that collects information from the reports and possibly other sources to provide that in a way that can be easily processed. The suggestion would be to use a structure that is compatible to JSON, to enable easy use outside the scope of hale studio.

In the first implementation the summary should contain information that we can easily access, e.g. the information from reports, which actions were run, if there were errors, warnings, etc.
Later it could be extended with additional information that can be used to analyse the transformation.

For specifying the success/failure conditions the idea is that the user can provide a file that states these conditions and relates to the transformation summary.
When the transformation is executed via the command line interface, the exit code should represent the result according to the success conditions.

In the process of this issue it seems also sensible to extend the report API with the notion of a task identifier added to a report, to better be able to identify specific reports.

This is a (not necessarily complete) list of tasks:

- [x] Add task identifier to reports
- [x] Add transformation summary API (maybe best to keep it generic, as there is also potential to use that for instance for CLI commands other than the transformation)
- [x] Add report information to transformation summary
- [x] Add information about total number of instances created in the transformation to the summary
- [x] Define how success conditions should be provided
- [x] Add support for evaluating success conditions

**Comment by stempler** [comment]
Here are early drafts of possible summary and success condition files structure (in this case YAML). They are intended to serve as inspiration, not as blueprint. Also, they only include information from reports and still assume that there are only report names available, not task identifiers.

Summary:
```yaml
Instance transformation:
  - completed: true
    errors: 0
    warnings: 0
Instance validation:
  - completed: true
    errors: 0
    warnings: 0
GML file export:
  - completed: true
    errors: 0
    warnings: 0
```

Conditions:
```yaml
Instance transformation:
  required: true
  failOnError: true
  failOnWarning: false
Instance validation:
  required: false
  failOnError: true
  failOnWarning: true
GML file export:
  required: true
  failOnError: true
  failOnWarning: false
```
